version: '2'
services:
  
  #Web App
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: webapp_img
    container_name: web_app
    ports:
      - "8080:80"
    #working_dir: /usr/share/nginx/html

  #Nginx Service
  webserver:
    image: nginx
    container_name: websvr-nginx
    #restart: unless-stopped
    ports:
      - "80:80"

  #MySQL Service
  db:
    image: mysql
    container_name: mysql-db
    #restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: webap_db
      MYSQL_ROOT_PASSWORD: 1234

  #to connect DB -> docker exec -it mysql-db mysql -u root -p
